#ifndef _POOL_DEFS_
#define _POOL_DEFS_

// DeluxeDelivery: level loading is only 50ms faster!

//#define USE_ANIMATION_POOL
//#define POOL_SIZE_GUI_ANIMATION								10000
//#define POOL_SIZE_GUI_ANIMATION_CONTAINER					100000
//#define POOL_SIZE_GUI_ANIMATION_CONTAINER_OF_PHYSICS		10000
//#define POOL_SIZE_GUI_ANIMATION_CONTAINER_OF_STENCIL		10000
//#define POOL_SIZE_GUI_ANIMATION_DESERIALIZE_PARAMETER		100000
//#define POOL_SIZE_GUI_ANIMATION_DUMMY						10000
//#define POOL_SIZE_GUI_ANIMATION_DUMMY_CONTAINER				10000
//#define POOL_SIZE_GUI_ANIMATION_EVENT						10000
//#define POOL_SIZE_GUI_ANIMATION_FILLED_RECTANGLE			10000
//#define POOL_SIZE_GUI_ANIMATION_LAYOUT_CONTAINER			10000
//#define POOL_SIZE_GUI_ANIMATION_MULTI_IMAGES				10000
//#define POOL_SIZE_GUI_ANIMATION_MUSIC						10000
//#define POOL_SIZE_GUI_ANIMATION_PARAMETER					10000
//#define POOL_SIZE_GUI_ANIMATION_PARTICLES_EMITTER			10000
//#define POOL_SIZE_GUI_ANIMATION_PHYSICS_BODIES_CONTAINER	100000
//#define POOL_SIZE_GUI_ANIMATION_PHYSICS_BODY				10000
//#define POOL_SIZE_GUI_ANIMATION_PHYSICS_CONTAINER			100000
//#define POOL_SIZE_GUI_ANIMATION_PHYSICS_JOINT				100000
//#define POOL_SIZE_GUI_ANIMATION_PHYSICS_LABEL				10000
//#define POOL_SIZE_GUI_ANIMATION_PHYSICS_GROUND				10000
//#define POOL_SIZE_GUI_ANIMATION_PHYSICS_MULTI_IMAGES		100000
//#define POOL_SIZE_GUI_ANIMATION_PHYSICS_STATIC_IMAGE		100000
//#define POOL_SIZE_GUI_ANIMATION_SCRIPT_PARAMETER_UPDATE		10000
//#define POOL_SIZE_GUI_ANIMATION_STATIC_IMAGE				100000
//#define POOL_SIZE_GUI_ANIMATION_GRADIENT					1000
//#define POOL_SIZE_GUI_ANIMATION_STENCIL_CONTAINER			10000
//#define POOL_SIZE_GUI_ANIMATOR								10000
//#define POOL_SIZE_GUI_ANIMATOR_KEY_BOOL_PARAMETER			10000
//#define POOL_SIZE_GUI_ANIMATOR_KEY_BOOL_PARAMETER_DATA		10000
//#define POOL_SIZE_GUI_ANIMATOR_KEY_FLOAT_PARAMETER			10000
//#define POOL_SIZE_GUI_ANIMATOR_KEY_FLOAT_PARAMETER_DATA		10000
//#define POOL_SIZE_GUI_ANIMATOR_KEY_SELECT_PARAMETER			10000
//#define POOL_SIZE_GUI_ANIMATOR_KEY_SELECT_PARAMETER_DATA	10000
//#define POOL_SIZE_GUI_ANIMATOR_SCRIPT_FLOAT_PARAMETER		10000
//
//#define POOL_SIZE_GUI_TAP_DATA								10000

#endif
