#ifndef _CC64KEYBOARDSHORTCUTS_H_
#define _CC64KEYBOARDSHORTCUTS_H_

#define KBZONE_GLOBAL	1
#define KBZONE_SETTINGS	2

//
typedef enum c64keyboardshortcuts
{
	KBFUN_MOVE_FOCUS_TO_NEXT_VIEW,
	KBFUN_MOVE_FOCUS_TO_PREV_VIEW,
	KBFUN_INSERT_D64,
	KBFUN_INSERT_CARTRIDGE,
	KBFUN_CARTRIDGE_FREEZE_BUTTON,
	KBFUN_LOAD_PRG,
	KBFUN_RELOAD_AND_RESTART,
	KBFUN_SOFT_RESET,
	KBFUN_HARD_RESET,
	KBFUN_BREAKPOINTS,
	KBFUN_LIMIT_SPEED,
	KBFUN_USE_KEYBOARD_AS_JOYSTICK,
	KBFUN_SETTINGS_SCREEN,
	KBFUN_STEP_OVER_INSTRUCTION,
//	KBFUN_STEP_OVER_JSR,	<- moved to ViewDisassemble
	KBFUN_STEP_ONE_CYCLE,
	KBFUN_RUN_CONTINUE_EMULATION,
	KBFUN_IS_DATA_DIRECTLY_FROM_RAM,
	KBFUN_IS_MULTICOLOR_DATA,
	KBFUN_IS_SHOW_RASTER_BEAM,
	KBFUN_SNAPSHOT_MENU,
	KBFUN_SAVE_SNAPSHOT,
	KBFUN_LOAD_SNAPSHOT,
	KBFUN_STORE_SNAPSHOT1,
	KBFUN_STORE_SNAPSHOT2,
	KBFUN_STORE_SNAPSHOT3,
	KBFUN_STORE_SNAPSHOT4,
	KBFUN_STORE_SNAPSHOT5,
	KBFUN_STORE_SNAPSHOT6,
	KBFUN_RESTORE_SNAPSHOT1,
	KBFUN_RESTORE_SNAPSHOT2,
	KBFUN_RESTORE_SNAPSHOT3,
	KBFUN_RESTORE_SNAPSHOT4,
	KBFUN_RESTORE_SNAPSHOT5,
	KBFUN_RESTORE_SNAPSHOT6,
	
	KBFUN_SCREEN_LAYOUT1,
	KBFUN_SCREEN_LAYOUT2,
	KBFUN_SCREEN_LAYOUT3,
	KBFUN_SCREEN_LAYOUT4,
	KBFUN_SCREEN_LAYOUT5,
	KBFUN_SCREEN_LAYOUT6,
	KBFUN_SCREEN_LAYOUT7,
	KBFUN_SCREEN_LAYOUT8,
	
	_KBFUN_LAST_
} C64KeyboardShortcuts;

#endif

