#ifndef _GFX_TYPES_H_
#define _GFX_TYPES_H_

#define GFX_BYTE_MAGIC1 'g'
#define GFX_FILE_VERSION	0x0001

#define GFX_FILE_TYPE_UNKNOWN	0x00
#define GFX_FILE_TYPE_RGBA	0x01

#define GFX_COMPRESSION_TYPE_UNCOMPRESSED 0x00
#define GFX_COMPRESSION_TYPE_LZMPI		0x01
#define GFX_COMPRESSION_TYPE_ZLIB		0x02
#define GFX_COMPRESSION_TYPE_JPEG		0x03
#define GFX_COMPRESSION_TYPE_JPEG_ZLIB 	0x04

#endif
